feat: configure release signing and enhance CI/CD workflow for backend authentication

diff --git a/.github/workflows/main_distributor.yaml b/.github/workflows/main_distributor.yaml
--- a/.github/workflows/main_distributor.yaml
+++ b/.github/workflows/main_distributor.yaml
@@ -61,4 +61,32 @@ jobs:
           draft: false
           prerelease: false
         env:
-          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_TOKEN: ${{ secrets.PUBLISH_TOKEN }}
+
+      - name: Authenticate and Notify Backend
+        run: |
+          LOGIN_RESPONSE=$(curl -s -X POST "${{ secrets.BACKEND_URL }}/api/v1/auth/login" \
+            -H "Content-Type: application/json" \
+            -d '{"username":"${{ secrets.CI_USER }}", "password":"${{ secrets.CI_PASSWORD }}"}')
+            
+            # 2. Extraer el token de la propiedad jwtToken
+            # Usamos jq para procesar el JSON de respuesta
+            TOKEN=$(echo $LOGIN_RESPONSE | jq -r '.jwtToken')
+            
+            # Verificación simple de seguridad
+            if [ "$TOKEN" == "null" ]; then
+              echo "Error: No se pudo obtener el JWT. Revisa las credenciales."
+              exit 1
+            fi
+            
+            # 3. Publicar la actualización usando el Token obtenido
+            curl -X POST "${{ secrets.BACKEND_URL }}/api/v1/app-versions" \
+              -H "Content-Type: application/json" \
+              -H "Authorization: Bearer $TOKEN" \
+              -d '{
+                "versionName": "v${{ env.VERSION }}",
+                "downloadUrl": "https://github.com/DevMinds-Development-Group/secretary/releases/latest/download/app-release.apk",
+                "publicId": "v${{ env.VERSION }}",
+                "releaseNotes": "Actualización menor con resolución de errores y mejoras de rendimiento.",
+                "isMandatory": true
+              }'
